// <auto-generated>Classes for JSON parsing</auto-generated>
#nullable enable
namespace Skyline.DataMiner.CICD.Tools.JenkinsMaintenance.JenkinsModels
{
    using System.Collections.Generic;
    using System.Text.Json.Serialization;

    internal class BuildQueue
    {
        public const string Tree = $"items[{QueueItem.Tree}]";

        [JsonPropertyName("items")]
        public List<QueueItem> Items { get; set; } = [];
    }

    internal class QueueItem
    {
        public const string Tree = "blocked,buildable,id,url,stuck";

        [JsonPropertyName("blocked")]
        public bool? Blocked { get; set; }

        [JsonPropertyName("buildable")]
        public bool? Buildable { get; set; }

        [JsonPropertyName("id")]
        public required long Id { get; set; }

        /// <summary>
        /// Not a full URL.
        /// <para>Example: <example>queue/item/{id}/</example></para>
        /// </summary>
        [JsonPropertyName("url")]
        public string? Url { get; set; }

        /// <summary>
        /// Will be true if e.g. all nodes are offline. Meaning that the job cannot be executed.
        /// </summary>
        [JsonPropertyName("stuck")]
        public bool? Stuck { get; set; }
    }
}