// <auto-generated>Classes for JSON parsing</auto-generated>
#nullable enable
namespace Skyline.DataMiner.CICD.Tools.JenkinsMaintenance.JenkinsModels
{
    using System.Collections.Generic;
    using System.Text.Json.Serialization;

    internal class Folder : Job
    {
        public new const string Tree = $"jobs[{SubJob.Tree}]";
        public const string FullTree = $"{Job.Tree},{Tree}";

        [JsonPropertyName("jobs")]
        public List<SubJob>? Jobs { get; set; }
    }

    internal class SubJob
    {
        public const string Tree = "url";

        [JsonPropertyName("url")]
        public string? Url { get; set; }
    }
}