// <auto-generated>Classes for JSON parsing</auto-generated>
#nullable enable
namespace Skyline.DataMiner.CICD.Tools.JenkinsMaintenance.JenkinsModels
{
    using System.Text.Json.Serialization;

    internal interface IJob
    {
        string? Name { get; set; }

        string? Description { get; set; }

        string Url { get; set; }

        string? DisplayName { get; set; }

        string? FullName { get; set; }
    }
}