// <auto-generated>Classes for JSON parsing</auto-generated>
#nullable enable
namespace Skyline.DataMiner.CICD.Tools.JenkinsMaintenance.JenkinsModels
{
    using System.Text.Json.Serialization;

    internal class Job : IJob
    {
        public const string Tree = "name,description,url,displayName,fullName";

        [JsonPropertyName("name")]
        public string? Name { get; set; }

        [JsonPropertyName("description")]
        public string? Description { get; set; }

        [JsonPropertyName("url")]
        public required string Url { get; set; }

        [JsonPropertyName("displayName")]
        public string? DisplayName { get; set; }

        [JsonPropertyName("fullName")]
        public string? FullName { get; set; }
    }
}