// <auto-generated>Classes for JSON parsing</auto-generated>
#nullable enable
namespace Skyline.DataMiner.CICD.Tools.JenkinsMaintenance.JenkinsModels
{
    using System.Text.Json.Serialization;

    internal class Node
    {
        public const string Tree = "description,displayName,idle,jnlpAgent,numExecutors,offline,offlineCauseReason,temporarilyOffline";

        [JsonIgnore]
        public string? UrlName { get; internal set; }

        [JsonPropertyName("description")]
        public string? Description { get; set; }

        [JsonPropertyName("displayName")]
        public required string DisplayName { get; set; }

        [JsonPropertyName("idle")]
        public bool? Idle { get; set; }

        [JsonPropertyName("jnlpAgent")]
        public bool? JnlpAgent { get; set; }

        [JsonPropertyName("numExecutors")]
        public int? NumExecutors { get; set; }

        [JsonPropertyName("offline")]
        public bool? IsOffline { get; set; }

        [JsonPropertyName("offlineCauseReason")]
        public string? OfflineCauseReason { get; set; }

        [JsonPropertyName("temporarilyOffline")]
        public bool? IsTemporarilyOffline { get; set; }
    }
}