// <auto-generated>Classes for JSON parsing</auto-generated>
#nullable enable
namespace Skyline.DataMiner.CICD.Tools.JenkinsMaintenance.JenkinsModels
{
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using Skyline.DataMiner.CICD.Tools.JenkinsMaintenance.Models;

    internal class Workflow : Job
    {
        public new const string Tree = $"buildable,builds[{WorkflowRun.Tree}]";

        public const string FullTree = $"{Job.Tree},{Tree}";

        /// <summary>
        /// Indicates whether the workflow is buildable aka, enabled or not.
        /// </summary>
        [JsonPropertyName("buildable")]
        public bool? IsEnabled { get; set; }

        [JsonPropertyName("builds")]
        public List<WorkflowRun>? Builds { get; set; }

        public int BuildCount => Builds?.Count ?? 0;
    }
}