// <auto-generated>Classes for JSON parsing</auto-generated>
#nullable enable
namespace Skyline.DataMiner.CICD.Tools.JenkinsMaintenance.Models
{
    using System.Text.Json.Serialization;

    internal class WorkflowRun
    {
        public const string Tree = "building,number,url,result";

        [JsonPropertyName("building")]
        public bool? Building { get; set; }
        
        [JsonPropertyName("number")]
        public required int Number { get; set; }

        [JsonPropertyName("url")]
        public required string Url { get; set; }

        [JsonPropertyName("result")]
        public string? Result { get; set; }
    }
}