// <auto-generated>Classes for JSON parsing</auto-generated>
#nullable enable
namespace Skyline.DataMiner.CICD.Tools.JenkinsMaintenance.Models
{
    using System.Collections.Generic;
    using System.Linq;
    using Skyline.DataMiner.CICD.Tools.JenkinsMaintenance.JenkinsModels;

    internal class GeneralInfo
    {
        public List<Node> Nodes { get; set;  } = [];

        public int NumberOfNodes => Nodes.Count;

        public List<Workflow> WorkFlows { get; set; } = [];

        public int NumberOfWorkflows => WorkFlows.Count;

        public Dictionary<string, int> OversizedWorkflows =>
            WorkFlows.Where(flow => flow.Builds?.Count > 100)
                     .ToDictionary(flow => flow.Url!, value => value.Builds!.Count);
    }
}